feat: adds transition shorthand
microsoft/griffel pull request #189
Opened 2022-08-05 11:56 UTC by bsunderhus

Fixes #177

2022-08-08 12:09 UTC, layershifter approved these changes
Small nits, other than that LGMT 👍

2022-08-08 12:09 UTC, layershifter commented on change/@griffel-core-cca9a4d2-a460-4d77-a750-b6dd381c37f5.json
> +  "comment": "feat: adds transition shorthand",
```suggestion
  "comment": "feat: add transition shorthand",
```

nit

2022-08-08 12:09 UTC, layershifter commented on packages/core/src/shorthands/types.ts
> +export type TransitionGlobalnInput = CSS.Globals;
```suggestion
export type TransitionGlobalInput = CSS.Globals;
```

Oops, a typo

2022-08-08 12:09 UTC, layershifter commented on packages/core/src/shorthands/transition.ts
> +];
nit: let's move `TransitionInputs` before `TransitionStyle`

2022-08-08 12:38 UTC, ling1726 requested changes
Please add some docs for this

2022-08-09 12:08 UTC, ling1726 commented
@bsunderhus  can you add documentation to the docsite ? https://github.com/microsoft/griffel/blob/main/apps/website/docs/react/api/shorthands.md

2022-08-09 14:21 UTC, bsunderhus commented
> @bsunderhus can you add documentation to the docsite ? https://github.com/microsoft/griffel/blob/main/apps/website/docs/react/api/shorthands.md

So many documentation files 🙈, apparently, I've missed that one! thx @ling1726

2022-08-09 18:15 UTC, ling1726 approved these changes

2022-08-10 06:31 UTC, merged